name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.3.1
  - scipy=1.15.3
  - flask=3.0.3
  - flask-cors=5.0.1
  - pip
  - pip:
      - bcrypt==4.3.0
      - beautifulsoup4==4.12.3
      - blinker==1.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.0
      - colorama==0.4.6
      - dnspython==2.7.0
      - Flask-Bcrypt==1.0.1
      - Flask-PyMongo==3.0.1
      - googlesearch-python==1.2.3
      - gunicorn==23.0.0
      - idna==3.10
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - joblib==1.5.0
      - MarkupSafe==3.0.2
      - packaging==25.0
      - PyJWT==2.10.1
      - pymongo==4.12.1
      - python-dateutil==2.8.2
      - python-dotenv==1.1.0
      - pytz==2025.2
      - requests==2.31.0
      - six==1.17.0
      - soupsieve==2.7
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - urllib3==2.2.1
      - Werkzeug==3.1.3
      - whois==0.9.27
